import './globals.css';
import { Nunito } from 'next/font/google';
import { Navbar } from './components/navbar/Navbar';
import 'tippy.js/dist/tippy.css';
import Footer from './components/footer/Footer';
import { ModalContextProvider } from './context/contactModalContext';

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['500', '600', '700', '800', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ModalContextProvider>
        <body className={nunito.className}>
          <Navbar />
          <div className="nav-bar-margin" />
          {children}
          <Footer />
        </body>
      </ModalContextProvider>
    </html>
  );
}
